name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - uses: pnpm/action-setup@v3
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps
      - name: Playwright tests
        run: pnpm run test:e2e
      - name: Lint
        run: pnpm run lint
      - name: Prettier
        run: pnpm run format
